"""Init repository_metrics and api_key schema

Revision ID: 503d219e8dc8
Revises: 
Create Date: 2026-04-01 19:35:30.248694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503d219e8dc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('valid_api_keys', sa.String(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_valid_api_keys'), 'api_key', ['valid_api_keys'], unique=True)
    op.create_table('repository_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_velocity_24h', sa.Integer(), nullable=False),
    sa.Column('open_issues_delta', sa.Integer(), nullable=False),
    sa.Column('fork_velocity_24h', sa.Integer(), nullable=False),
    sa.Column('contributor_churn', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'timestamp', name='uix_repo_time')
    )
    op.create_index(op.f('ix_repository_metrics_repo_name'), 'repository_metrics', ['repo_name'], unique=False)
    op.create_index(op.f('ix_repository_metrics_timestamp'), 'repository_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_metrics_timestamp'), table_name='repository_metrics')
    op.drop_index(op.f('ix_repository_metrics_repo_name'), table_name='repository_metrics')
    op.drop_table('repository_metrics')
    op.drop_index(op.f('ix_api_key_valid_api_keys'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
