"""rev2_package_risk_metrics

Revision ID: 8a31c7e4b60b
Revises: 503d219e8dc8
Create Date: 2026-07-26 16:42:01.763447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a31c7e4b60b'
down_revision: Union[str, Sequence[str], None] = '503d219e8dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_risk_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_velocity_24h', sa.Integer(), nullable=False),
    sa.Column('open_issues_delta', sa.Integer(), nullable=False),
    sa.Column('fork_velocity_24h', sa.Integer(), nullable=False),
    sa.Column('contributor_churn', sa.Float(), nullable=False),
    sa.Column('maintainer_count', sa.Integer(), nullable=True),
    sa.Column('single_maintainer_flag', sa.Boolean(), nullable=False),
    sa.Column('days_since_last_publish', sa.Integer(), nullable=True),
    sa.Column('publish_cadence_variance', sa.Float(), nullable=True),
    sa.Column('fork_spike_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_name', 'timestamp', name='uix_package_time')
    )
    op.create_index(op.f('ix_package_risk_metrics_package_name'), 'package_risk_metrics', ['package_name'], unique=False)
    op.create_index(op.f('ix_package_risk_metrics_timestamp'), 'package_risk_metrics', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_repository_metrics_repo_name'), table_name='repository_metrics')
    op.drop_index(op.f('ix_repository_metrics_timestamp'), table_name='repository_metrics')
    op.drop_table('repository_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_metrics',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('repo_name', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('commit_velocity_24h', sa.INTEGER(), nullable=False),
    sa.Column('open_issues_delta', sa.INTEGER(), nullable=False),
    sa.Column('fork_velocity_24h', sa.INTEGER(), nullable=False),
    sa.Column('contributor_churn', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'timestamp', name=op.f('uix_repo_time'))
    )
    op.create_index(op.f('ix_repository_metrics_timestamp'), 'repository_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_repository_metrics_repo_name'), 'repository_metrics', ['repo_name'], unique=False)
    op.drop_index(op.f('ix_package_risk_metrics_timestamp'), table_name='package_risk_metrics')
    op.drop_index(op.f('ix_package_risk_metrics_package_name'), table_name='package_risk_metrics')
    op.drop_table('package_risk_metrics')
    # ### end Alembic commands ###
